// <auto-generated />
using System;
using FieldMonitoring.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FieldMonitoring.Infrastructure.Migrations
{
    [DbContext(typeof(FieldMonitoringDbContext))]
    [Migration("20260122230322_DatetimeOffset")]
    partial class DatetimeOffset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FieldMonitoring.Domain.Alerts.Alert", b =>
                {
                    b.Property<Guid>("AlertId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FarmId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FieldId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("Severity")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AlertId");

                    b.HasIndex("FarmId", "Status");

                    b.HasIndex("FieldId", "StartedAt");

                    b.HasIndex("FieldId", "AlertType", "Status");

                    b.ToTable("Alerts", (string)null);
                });

            modelBuilder.Entity("FieldMonitoring.Domain.Fields.Field", b =>
                {
                    b.Property<string>("FieldId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FarmId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double?>("LastAirHumidity")
                        .HasColumnType("float");

                    b.Property<double?>("LastAirTemperature")
                        .HasColumnType("float");

                    b.Property<double?>("LastRain")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset?>("LastReadingAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<double?>("LastSoilMoisture")
                        .HasColumnType("float");

                    b.Property<double?>("LastSoilTemperature")
                        .HasColumnType("float");

                    b.Property<DateTimeOffset?>("LastTimeAboveDryAirThreshold")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastTimeAboveDryThreshold")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastTimeAboveFrostThreshold")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastTimeBelowHeatThreshold")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastTimeBelowHumidAirThreshold")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SensorId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("StatusReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("FieldId");

                    b.HasIndex("FarmId");

                    b.HasIndex("Status");

                    b.HasIndex("FarmId", "Status");

                    b.ToTable("Fields", (string)null);
                });

            modelBuilder.Entity("FieldMonitoring.Domain.Telemetry.ProcessedReading", b =>
                {
                    b.Property<string>("ReadingId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FieldId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("ProcessedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("ReadingId");

                    b.HasIndex("FieldId");

                    b.ToTable("ProcessedReadings", (string)null);
                });

            modelBuilder.Entity("FieldMonitoring.Domain.Alerts.Alert", b =>
                {
                    b.HasOne("FieldMonitoring.Domain.Fields.Field", null)
                        .WithMany("Alerts")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FieldMonitoring.Domain.Fields.Field", b =>
                {
                    b.Navigation("Alerts");
                });
#pragma warning restore 612, 618
        }
    }
}
